AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Verify no AWS or other secrets are in the target git/Github repository.
Resources:
  RepositoryScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: repositoryscan.handler
      Runtime: python3.6
      CodeUri: repositoryscan.zip
